### ISSUE TITLE
Need to update to support chef 13

### ISSUE THREAD

**Issue by joshoohaah** [juliandunn/yum-oracle#1]
getting a handful of errors when I run this cookbook against chef-client v `12.5.1`.

Here are the outputs:

```
  mirrorlist nil currently does not overwrite the value of mirrorlist. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :mirrorlist, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:37:in `block (2 levels) in from_file'
  cost nil currently does not overwrite the value of cost. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :cost, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:41:in `block (2 levels) in from_file'
  exclude nil currently does not overwrite the value of exclude. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :exclude, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:42:in `block (2 levels) in from_file'
  enablegroups nil currently does not overwrite the value of enablegroups. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :enablegroups, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:43:in `block (2 levels) in from_file'
  failovermethod nil currently does not overwrite the value of failovermethod. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :failovermethod, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:44:in `block (2 levels) in from_file'
  http_caching nil currently does not overwrite the value of http_caching. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :http_caching, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:45:in `block (2 levels) in from_file'
  include_config nil currently does not overwrite the value of include_config. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :include_config, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:46:in `block (2 levels) in from_file'
  includepkgs nil currently does not overwrite the value of includepkgs. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :includepkgs, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:47:in `block (2 levels) in from_file'
  keepalive nil currently does not overwrite the value of keepalive. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :keepalive, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:48:in `block (2 levels) in from_file'
  max_retries nil currently does not overwrite the value of max_retries. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :max_retries, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:49:in `block (2 levels) in from_file'
  mirror_expire nil currently does not overwrite the value of mirror_expire. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :mirror_expire, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:51:in `block (2 levels) in from_file'
  priority nil currently does not overwrite the value of priority. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :priority, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:52:in `block (2 levels) in from_file'
  proxy nil currently does not overwrite the value of proxy. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :proxy, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:53:in `block (2 levels) in from_file'
  proxy_username nil currently does not overwrite the value of proxy_username. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :proxy_username, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:54:in `block (2 levels) in from_file'
  proxy_password nil currently does not overwrite the value of proxy_password. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :proxy_password, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:55:in `block (2 levels) in from_file'
  sslcacert nil currently does not overwrite the value of sslcacert. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :sslcacert, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:57:in `block (2 levels) in from_file'
  sslclientcert nil currently does not overwrite the value of sslclientcert. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :sslclientcert, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:58:in `block (2 levels) in from_file'
  sslclientkey nil currently does not overwrite the value of sslclientkey. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :sslclientkey, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:59:in `block (2 levels) in from_file'
  sslverify nil currently does not overwrite the value of sslverify. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :sslverify, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:60:in `block (2 levels) in from_file'
  timeout nil currently does not overwrite the value of timeout. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :timeout, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/yum-oracle/recipes/default.rb:61:in `block (2 levels) in from_file'
```

**Comment by juliandunn** [comment]
Closed in #2
